# Site settings

title: ONEAL Project 
description: >- # this means to ignore newlines until "baseurl:"
  Open Negotiation Education for Academic Libraries (ONEAL) is generously funded through the Institute of Museum and Library Services.
baseurl: "/Grants" # the subpath of your site, e.g. /blog
url: "localhost:4000/Grants/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
